language: php
php:
  - '7.0'
  - '7.1'

install:
  - travis_retry composer install --no-interaction

before_script:
    - mkdir -p build/merge
    - mkdir -p build/logs

script:
  - ./bin/phpunit --coverage-clover build/merge/phpunit.xml
  - ./bin/phpspec run
  - ./bin/phpcov merge ./build/merge --clover ./build/logs/clover.xml

after_success:
  - rm -rf ./build/merge
  - cat ./build/logs/clover.xml
  - travis_retry ./bin/coveralls -v

branches:
  only: master