language: php
php:
  - '7.0'
  - '7.1'

install:
  - travis_retry composer install --no-interaction

before_script:
    - mkdir -p build/merge
    - mkdir -p build/logs

script:
  - composer test
  - ./bin/phpcov merge ./build/merge --clover ./build/logs/clover.xml

after_success:
  - ./bin/coveralls -v -r $PWD

branches:
  only: master